StudyConfirmationProject/StudyConfirmationProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
#from practiceapp.views import logout, login

urlpatterns = [
    url(r'^practiceapp/', include('practiceapp.urls', namespace="practiceapp")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', login),
    url(r'^login/$',  login),
    url(r'^logout/$', logout),
    url(r'^accounts/profile/', include('practiceapp.urls'))
]

StudyConfirmationProject/practiceapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<certificate_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.contact, name='contact'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^requests/$', views.requests, name='requests')
]

StudyConfirmationProject/practiceapp/models.py
from datetime import timezone

from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User

# Create your models here.

class Certificate(models.Model):
    certificate_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.certificate_text


class RequestManager(models.Manager):
    def create_request(self, certificate, group, name, surname, father_name, amount):
        request = self.create(certificate=certificate, group=group, name=name, surname=surname, father_name=father_name, amount=amount, pub_date= timezone.now())
        return request


class Request(models.Model):
    certificate = models.ForeignKey(Certificate)
    group = models.CharField(max_length=10)
    surname = models.CharField(max_length=20)
    name = models.CharField(max_length=10)
    fathername = models.CharField(max_length=20)
    amount = models.IntegerField(default=1)
    pub_date = models.DateTimeField('date published')

    objects = RequestManager()

    def __str__(self):
        return self.surname


class CertificateForm(ModelForm):
    class Meta:
        model = Certificate
        fields = '__all__'

class MySiteProfile(models.Model):
    user = models.OneToOneField(User)
    father_name = models.CharField(max_length=20)
    group = models.CharField(max_length=20)

    def __unicode__(self):
        return self.user

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

StudyConfirmationProject/practiceapp/forms.py
from django import forms

class ContactForm(forms.Form):
    amount = forms.IntegerField(label='Количество экземпляров')

StudyConfirmationProject/practiceapp/views.py
from datetime import timezone

from django.shortcuts import render_to_response, render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views import generic
from django.views.generic import FormView
from .models import Certificate, Request
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import authenticate
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.shortcuts import render
from django.core.mail import send_mail
from practiceapp.forms import ContactForm
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import auth

def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = auth.authenticate(username=username, password=password)
    if user is not None and user.is_active:
        # Правильный пароль и пользователь "активен"
        auth.login(request, user)
        # Перенаправление на "правильную" страницу
        return HttpResponseRedirect("/account/loggedin/")
    else:
        # Отображение страницы с ошибкой
        return HttpResponseRedirect("/account/invalid/")

@login_required
def index(request):
    if request.user.groups.filter(name='Students'):
        latest_certificate_list = Certificate.objects.order_by('-pub_date')[:100]
        context = {'latest_certificate_list': latest_certificate_list}
        return render(request, 'practiceapp/index.html', context)
    else:
        return render(request, 'registration/login.html')

@login_required
def detail(request, certificate_id):
    if request.user.groups.filter(name='Students'):
        certificate = get_object_or_404(Certificate, pk=certificate_id)
        return render(request, 'practiceapp/contact_form.html', {'certificate': certificate})
    else:
        return render(request, 'registration/login.html')

@login_required
def contact(request):
    if request.user.groups.filter(name='Students'):
        if request.method == 'POST':
            form = ContactForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                request = Request.objects.create_request(request.certificate_id , request.user.mysiteprofile.group, request.user.last_name, request.user.first_name, request.user.mysiteprofile.father_name, cd, timezone.now())
                request.save()
            return HttpResponseRedirect('/practiceapp/thanks/')
            #return render_to_response('practiceapp/contact_form.html', {'form': form})
        else:
            form = ContactForm(
            )
        return render_to_response('practiceapp/contact_form.html', {'form': form})
    else:
        return render(request, 'registration/login.html')

@login_required
def thanks(request):
    if request.user.groups.filter(name='Students'):
        return render_to_response('practiceapp/thanks_form.html')
    else:
        return render(request, 'registration/login.html')

def logout(request):
    if request.user.groups.filter(name='Students'):
        auth.logout(request)
        return render_to_response('registration/logout.html')
    else:
        return render(request, 'registration/login.html')

@login_required
def requests(request):
    if request.user.groups.filter(name='Deanery'):
        latest_requests_list = Request.objects.order_by('-pub_date')[:5]
        context = {'latest_requests_list': latest_requests_list}
        return render(request, 'practiceapp/requests.html', context)
    else:
        return render(request, 'registration/login.html')

StudyConfirmationProject/practiceapp/templates/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Форма Авторизации</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
    <div class="page-header">
        <h1><a href="/">Форма Авторизации</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

StudyConfirmationProject/practiceapp/templates/practiceapp/contact_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Заявка</title>
    <link rel="stylesheet" type="text/css" href="style/style.css" />
</head>
<body>
<h1>{{ certificate.certificate_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

<p>Группа:{{ request.user.mysiteprofile.group}}</p>
<p>Фамилия:{{ request.user.last_name }}</p>
<p>Имя:{{ request.user.first_name }}</p>
<p>Отчество:{{ request.user.mysiteprofile.father_name }}</p>
<form action="{% url 'practiceapp:thanks' %}" method="post">{% csrf_token %}
    <label>
        Количество справок:
        <input type="number" name="amount" value="{{ amount }}">
    </label>
    <br>
    <input type="submit" value="Submit">
</form>
</body>
</html>

StudyConfirmationProject/practiceapp/templates/practiceapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список</title>
    <link rel="stylesheet" type="text/css" href="style/style.css" />
    <!--<link href="F:\Bootstrap\ball\css\bootstrap.min.css" rel="stylesheet" media="screen">-->
</head>
<body>
    <p>Выберите нужную вам справку</p>
{% if latest_certificate_list %}
    <ul>
    {% for certificate in latest_certificate_list %}
    <li><a href="{% url 'practiceapp:contact' certificate.id %}">{{ certificate.certificate_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Нет справок.</p>
{% endif %}
</body>
</html>

StudyConfirmationProject/practiceapp/templates/practiceapp/requests.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Поданные заявки</title>
</head>
<body>
    <h1><strong>Здесь вы, сотрудник деканата, видите поданные студентами заявки на справки.</strong></h1>
{% if latest_requests_list %}
    <ul>
    {% for request in latest_requests_list %}
    <li>{{ request.certificate }}   {{ request.group }}     {{ request.surname }}     {{ request.name }}     {{ request.fathername }}     {{ request.amount }}     {{ request.pub_date }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>Нет заявок.</p>
{% endif %}
</body>
</html>

StudyConfirmationProject/practiceapp/templates/practiceapp/thanks_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thanks</title>
</head>
<body>
    <strong>Спасибо, что оставили заявку.</strong>
    <br>
    <a href="{% url 'practiceapp:index' %}">Если хотите оставить ещё одну заявку, перейдите по ссылке.</a>
</body>
</html>